name: .NET

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: 建立.netcore环境
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.407

    - name: 安装依赖
      run: dotnet restore

    - name: 构建
      run: dotnet build --configuration Release --no-restore

    - name: 打包
      run: dotnet pack

    - name: 发布生成包到nuget
      run: |
        dotnet nuget push ./src/WWB.Paylink.BaoFooPay/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NUGETKEY }}
        dotnet nuget push ./src/WWB.Paylink.BaoFooTransfer/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NUGETKEY }}
        dotnet nuget push ./src/WWB.Paylink.Utility/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NUGETKEY }}
        dotnet nuget push ./src/WWB.Paylink.JoinPay/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NUGETKEY }}
        dotnet nuget push ./src/WWB.Paylink.Baofu/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NUGETKEY }}

      
